version: '3'
services:
    eevoting:
        build: ./
        image: eevoting
        ports:
            - 8545:8545
            - 8540:8540
        volumes:
            - ../:/this_project
            - ./.vimrc:/root/.vimrc
        command: /this_project/docker/enter-point.sh
